### ISSUE TITLE
 Deployment on Heroku

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22-R#1]
## 2. Deployment on Heroku
rubric={accuracy:8}

**There are currently some issues with dash-r deployment
because plotly updated their docker images,
but not their documentation,
so neither the official setup or the one from last year's class is working at the moment.
I will give an update on lecture 6 on Wed if we can figure this out before then.**

- Deploy your app on Heroku
  and **include the link to your deployed dashboard clearly visible near the top of your README**.
- Don't push to Heroku after the milestone deadline.
    - We will compare the milestone release commits with the deployed app
      so updating it after the deadline will give a late penalty.
      If you want your newest changes deployed online,
      you can create a new heroku repo.
- Heroku does not have native support for R
  so we will need to use a docker image provided by Dash.
    - We will [follow the dash docs](https://dashr.plotly.com/deployment).
        - You need to change the `Dockerfile`
          to make sure you get version `3.6.3` of the docker image instead of `3.6.2`.
    - Because of this,
      I don't want to change the file structure from the docs,
      so put your `app.R` in the root project folder
      (together with all other files mentioned in the deployment docs),
    - Any other folders can be the same as for your Python project.
- Don't wait to deploy until Saturday night,
  you will not have time to solve potential issues.
    - Deploy early and check that things are working,
      then redeploy every now and then.
    - After making the milestone release,
      make a final push to Heroku to redeploy the miletone app.
    - This is especially important for R,
      since it takes about 15 min for the docker image to deploy.

**Comment by spentelow** [comment]
App deployed on Heroku.  Link is in readme.md
